// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddLogEntry(arg1:main.LogEntry):Promise<void>;

export function ClearLogs():Promise<void>;

export function GetCurrentSession():Promise<string>;

export function GetFileInfo(arg1:string):Promise<main.FileInfo>;

export function GetLogEntries():Promise<Array<main.LogEntry>>;

export function GetPlaybackConfig():Promise<Record<string, any>>;

export function GetRecordedFiles():Promise<Array<main.FileInfo>>;

export function GetRecordingConfig():Promise<Record<string, any>>;

export function GetRecordingsPath():Promise<string>;

export function GetServerAddress():Promise<string>;

export function IsPlaying():Promise<boolean>;

export function IsRecording():Promise<boolean>;

export function SelectFolder():Promise<string>;

export function SetPlaybackConfig(arg1:number,arg2:number,arg3:number,arg4:boolean):Promise<void>;

export function SetRecordingConfig(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetRecordingsPath(arg1:string):Promise<void>;

export function SetSessionName(arg1:string):Promise<void>;

export function StartPlayback(arg1:string,arg2:string,arg3:number):Promise<void>;

export function StartRecording(arg1:number):Promise<void>;

export function StopPlayback():Promise<void>;

export function StopRecording():Promise<void>;
