// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLogEntry(arg1) {
  return window['go']['main']['App']['AddLogEntry'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetLogEntries() {
  return window['go']['main']['App']['GetLogEntries']();
}

export function GetPlaybackConfig() {
  return window['go']['main']['App']['GetPlaybackConfig']();
}

export function GetRecordedFiles() {
  return window['go']['main']['App']['GetRecordedFiles']();
}

export function GetRecordingConfig() {
  return window['go']['main']['App']['GetRecordingConfig']();
}

export function GetRecordingsPath() {
  return window['go']['main']['App']['GetRecordingsPath']();
}

export function GetServerAddress() {
  return window['go']['main']['App']['GetServerAddress']();
}

export function IsPlaying() {
  return window['go']['main']['App']['IsPlaying']();
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetPlaybackConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetPlaybackConfig'](arg1, arg2, arg3, arg4);
}

export function SetRecordingConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRecordingConfig'](arg1, arg2, arg3);
}

export function SetRecordingsPath(arg1) {
  return window['go']['main']['App']['SetRecordingsPath'](arg1);
}

export function SetSessionName(arg1) {
  return window['go']['main']['App']['SetSessionName'](arg1);
}

export function StartPlayback(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartPlayback'](arg1, arg2, arg3);
}

export function StartRecording(arg1) {
  return window['go']['main']['App']['StartRecording'](arg1);
}

export function StopPlayback() {
  return window['go']['main']['App']['StopPlayback']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
